In [20]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'age': [20, np.nan, 30],
    'score': [80, np.nan, 90]
})
df

    age  score
0  20.0   80.0
1   NaN    NaN
2  30.0   90.0

In [ ]:
print(df.isnull())  #isnull=isna

     age  score
0  False  False
1   True   True
2  False  False

In [22]:
print(df.isnull().sum())

age      1
score    1
dtype: int64

In [23]:
df2 = df.dropna()
print(df2)

    age  score
0  20.0   80.0
2  30.0   90.0

In [24]:
df2 = df.fillna(0)
print(df2)

    age  score
0  20.0   80.0
1   0.0    0.0
2  30.0   90.0

In [25]:
df2 = df.copy()
df2['score'] = df['score'].fillna(0)
print(df2)

    age  score
0  20.0   80.0
1   NaN    0.0
2  30.0   90.0

In [26]:
df2 = df.copy()
avg = df2['age'].mean()
df2['age'] = df2['age'].fillna(avg)
print(df2)

    age  score
0  20.0   80.0
1  25.0    NaN
2  30.0   90.0

In [32]:
print(df['age'].isnull())

0    False
1     True
2    False
Name: age, dtype: bool

In [30]:
df

    age  score
0  20.0   80.0
1   NaN    NaN
2  30.0   90.0