In [1]:
import pandas as pd

data = {
    '이름': ['철수','영희','민수','지영','수진'],
    '나이': [25, 30, 19, 22, 28],
    '점수': [82, 91, 67, 74, 88],
    '출석률': [0.95, 0.88, 0.76, 0.92, 0.85]
}
df=pd.DataFrame(data)
df

   이름  나이  점수   출석률
0  철수  25  82  0.95
1  영희  30  91  0.88
2  민수  19  67  0.76
3  지영  22  74  0.92
4  수진  28  88  0.85

In [2]:
#점수 구간 파생변수
df['등급'] = 'C' #새로운 변수추가
df.loc[df['점수']>=80, '등급']='B'
    #loc[행, 열]
df.loc[df['점수']>=90, '등급']='A'
df

   이름  나이  점수   출석률 등급
0  철수  25  82  0.95  B
1  영희  30  91  0.88  A
2  민수  19  67  0.76  C
3  지영  22  74  0.92  C
4  수진  28  88  0.85  B

In [3]:
df['성인여부']=df['나이']>=20
df

   이름  나이  점수   출석률 등급   성인여부
0  철수  25  82  0.95  B   True
1  영희  30  91  0.88  A   True
2  민수  19  67  0.76  C  False
3  지영  22  74  0.92  C   True
4  수진  28  88  0.85  B   True

In [4]:
df['출석통과']=df['출석률']>=0.9
df

   이름  나이  점수   출석률 등급   성인여부   출석통과
0  철수  25  82  0.95  B   True   True
1  영희  30  91  0.88  A   True  False
2  민수  19  67  0.76  C  False  False
3  지영  22  74  0.92  C   True   True
4  수진  28  88  0.85  B   True  False

In [5]:
# 최종합격 여부 = (점수) + (출석률)
df['최종합격']=(df['점수']>=80) & (df['출석률']>=0.9)
df

   이름  나이  점수   출석률 등급   성인여부   출석통과   최종합격
0  철수  25  82  0.95  B   True   True   True
1  영희  30  91  0.88  A   True  False  False
2  민수  19  67  0.76  C  False  False  False
3  지영  22  74  0.92  C   True   True  False
4  수진  28  88  0.85  B   True  False  False

In [6]:
df['보정점수']=df['점수']+(df['출석률']*10)
df

   이름  나이  점수   출석률 등급   성인여부   출석통과   최종합격  보정점수
0  철수  25  82  0.95  B   True   True   True  91.5
1  영희  30  91  0.88  A   True  False  False  99.8
2  민수  19  67  0.76  C  False  False  False  74.6
3  지영  22  74  0.92  C   True   True  False  83.2
4  수진  28  88  0.85  B   True  False  False  96.5