In [1]:
import pandas as pd

data={
    '이름':['철수','영희','민수','지영','수진'],
    '점수':[82, 91, 150, 74, 88],
    '나이':[25, 30, 22, 120, 28]
}
df = pd.DataFrame(data)
df

   이름   점수   나이
0  철수   82   25
1  영희   91   30
2  민수  150   22
3  지영   74  120
4  수진   88   28

In [2]:
#IQR 방식 이상치 처리
Q1=df['점수'].quantile(0.25)
Q3=df['점수'].quantile(0.75)
IQR = Q3 - Q1
#박스길이의 위아래 1.5배를 넘어가면 이상치로 처리하여 제거
lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

df= df[(df['점수']>=lower) & (df['점수']<=upper)]
df

   이름  점수   나이
0  철수  82   25
1  영희  91   30
3  지영  74  120
4  수진  88   28

In [3]:
df=df[df['나이']<=100]
df

   이름  점수  나이
0  철수  82  25
1  영희  91  30
4  수진  88  28

In [4]:
df=df['나이']<=100
df

0    True
1    True
4    True
Name: 나이, dtype: bool