In [3]:
import pandas as pd

df= pd.DataFrame({
    'name': ['김철수','김대희','송영민','이희연','정미숙'],
    'weight': [80.0, 70.4, 65.5, 45.9, 51.2],
    'height': [170, 180, 155, 143, 154],
    'gender': ['m','m','m','f','f']
})
df
# print(df)

  name  weight  height gender
0  김철수    80.0     170      m
1  김대희    70.4     180      m
2  송영민    65.5     155      m
3  이희연    45.9     143      f
4  정미숙    51.2     154      f

In [5]:
# df['weight']
df.weight
print(df['weight'])

0    80.0
1    70.4
2    65.5
3    45.9
4    51.2
Name: weight, dtype: float64

In [6]:
df[['weight','height']]

   weight  height
0    80.0     170
1    70.4     180
2    65.5     155
3    45.9     143
4    51.2     154

In [7]:
df[df.height>=170]

  name  weight  height gender
0  김철수    80.0     170      m
1  김대희    70.4     180      m

In [8]:
df[df.gender=='m']

  name  weight  height gender
0  김철수    80.0     170      m
1  김대희    70.4     180      m
2  송영민    65.5     155      m

In [9]:
print(df.sort_values(by='height'))

  name  weight  height gender
3  이희연    45.9     143      f
4  정미숙    51.2     154      f
2  송영민    65.5     155      m
0  김철수    80.0     170      m
1  김대희    70.4     180      m

In [10]:
print(df.sort_values(by='weight', ascending=False))

  name  weight  height gender
0  김철수    80.0     170      m
1  김대희    70.4     180      m
2  송영민    65.5     155      m
4  정미숙    51.2     154      f
3  이희연    45.9     143      f

In [11]:
df.describe()

          weight      height
count   5.000000    5.000000
mean   62.600000  160.400000
std    13.971936   14.570518
min    45.900000  143.000000
25%    51.200000  154.000000
50%    65.500000  155.000000
75%    70.400000  170.000000
max    80.000000  180.000000

In [12]:
import pandas as pd
df=pd.read_csv('c:/data/traffic/data.csv',encoding='ms949')
df.head()
# df

,연번,호선,역번호,역명,2021년1월,2021년2월,2021년3월,2021년4월,2021년5월,2021년6월,2021년7월,2021년8월,2021년9월,2021년10월,2021년11월,2021년12월
0,1,1,150,서울역(1),1418813.0,1472401.0,1827089.0,1841712.0,1841724.0,1904825.0,1620121.0,1558341.0,1594971.0,1875753.0,2120803.0,1982088
1,2,1,151,시청(1),746651.0,748663.0,954481.0,955202.0,902354.0,964036.0,855752.0,804201.0,808826.0,912079.0,1063899.0,1020463
2,3,1,152,종각,1241008.0,1276854.0,1598997.0,1572365.0,1522428.0,1620980.0,1406282.0,1315179.0,1283699.0,1457135.0,1683022.0,1599339
3,4,1,153,종로3가(1),784896.0,851236.0,1084476.0,1059282.0,1053215.0,1071181.0,958835.0,938568.0,944294.0,1080723.0,1107875.0,1032603
4,5,1,154,종로5가,848774.0,861209.0,1100841.0,1071587.0,1057283.0,1089805.0,970424.0,918271.0,939937.0,1055802.0,1078896.0,1051190

In [13]:
del df['역번호']
print(df.head())

   연번  호선       역명    2021년1월    2021년2월    2021년3월    2021년4월    2021년5월  \
0   1   1   서울역(1)  1418813.0  1472401.0  1827089.0  1841712.0  1841724.0
1   2   1    시청(1)   746651.0   748663.0   954481.0   955202.0   902354.0
2   3   1       종각  1241008.0  1276854.0  1598997.0  1572365.0  1522428.0
3   4   1  종로3가(1)   784896.0   851236.0  1084476.0  1059282.0  1053215.0
4   5   1     종로5가   848774.0   861209.0  1100841.0  1071587.0  1057283.0

     2021년6월    2021년7월    2021년8월    2021년9월   2021년10월   2021년11월  2021년12월
0  1904825.0  1620121.0  1558341.0  1594971.0  1875753.0  2120803.0   1982088
1   964036.0   855752.0   804201.0   808826.0   912079.0  1063899.0   1020463
2  1620980.0  1406282.0  1315179.0  1283699.0  1457135.0  1683022.0   1599339
3  1071181.0   958835.0   938568.0   944294.0  1080723.0  1107875.0   1032603
4  1089805.0   970424.0   918271.0   939937.0  1055802.0  1078896.0   1051190

In [14]:
df2=df.drop(0)
df2.head()

,연번,호선,역명,2021년1월,2021년2월,2021년3월,2021년4월,2021년5월,2021년6월,2021년7월,2021년8월,2021년9월,2021년10월,2021년11월,2021년12월
1,2,1,시청(1),746651.0,748663.0,954481.0,955202.0,902354.0,964036.0,855752.0,804201.0,808826.0,912079.0,1063899.0,1020463
2,3,1,종각,1241008.0,1276854.0,1598997.0,1572365.0,1522428.0,1620980.0,1406282.0,1315179.0,1283699.0,1457135.0,1683022.0,1599339
3,4,1,종로3가(1),784896.0,851236.0,1084476.0,1059282.0,1053215.0,1071181.0,958835.0,938568.0,944294.0,1080723.0,1107875.0,1032603
4,5,1,종로5가,848774.0,861209.0,1100841.0,1071587.0,1057283.0,1089805.0,970424.0,918271.0,939937.0,1055802.0,1078896.0,1051190
5,6,1,동대문(1),410367.0,421973.0,518941.0,516203.0,534078.0,522532.0,469495.0,441862.0,472868.0,514705.0,521824.0,494419

In [15]:
df2=df.drop(['연번','호선'], axis=1) #axis=1세로/axis=0가로
df2.head()

,역명,2021년1월,2021년2월,2021년3월,2021년4월,2021년5월,2021년6월,2021년7월,2021년8월,2021년9월,2021년10월,2021년11월,2021년12월
0,서울역(1),1418813.0,1472401.0,1827089.0,1841712.0,1841724.0,1904825.0,1620121.0,1558341.0,1594971.0,1875753.0,2120803.0,1982088
1,시청(1),746651.0,748663.0,954481.0,955202.0,902354.0,964036.0,855752.0,804201.0,808826.0,912079.0,1063899.0,1020463
2,종각,1241008.0,1276854.0,1598997.0,1572365.0,1522428.0,1620980.0,1406282.0,1315179.0,1283699.0,1457135.0,1683022.0,1599339
3,종로3가(1),784896.0,851236.0,1084476.0,1059282.0,1053215.0,1071181.0,958835.0,938568.0,944294.0,1080723.0,1107875.0,1032603
4,종로5가,848774.0,861209.0,1100841.0,1071587.0,1057283.0,1089805.0,970424.0,918271.0,939937.0,1055802.0,1078896.0,1051190

In [16]:
# 행선택
df.loc[3] 
# print(df.loc[1])

연번                  4
호선                  1
역명            종로3가(1)
2021년1월      784896.0
2021년2월      851236.0
2021년3월     1084476.0
2021년4월     1059282.0
2021년5월     1053215.0
2021년6월     1071181.0
2021년7월      958835.0
2021년8월      938568.0
2021년9월      944294.0
2021년10월    1080723.0
2021년11월    1107875.0
2021년12월      1032603
Name: 3, dtype: object

In [17]:
df[0:3]

,연번,호선,역명,2021년1월,2021년2월,2021년3월,2021년4월,2021년5월,2021년6월,2021년7월,2021년8월,2021년9월,2021년10월,2021년11월,2021년12월
0,1,1,서울역(1),1418813.0,1472401.0,1827089.0,1841712.0,1841724.0,1904825.0,1620121.0,1558341.0,1594971.0,1875753.0,2120803.0,1982088
1,2,1,시청(1),746651.0,748663.0,954481.0,955202.0,902354.0,964036.0,855752.0,804201.0,808826.0,912079.0,1063899.0,1020463
2,3,1,종각,1241008.0,1276854.0,1598997.0,1572365.0,1522428.0,1620980.0,1406282.0,1315179.0,1283699.0,1457135.0,1683022.0,1599339

In [20]:
# 열선택
print(df.iloc[:,2])

0        서울역(1)
1         시청(1)
2            종각
3       종로3가(1)
4          종로5가
         ...
289        송파나루
290        한성백제
291    올림픽공원(9)
292        둔촌오륜
293      중앙보훈병원
Name: 역명, Length: 294, dtype: object

In [21]:
# 인덱스로 찾기 [행,열]
df.iloc[3:5, 0:2]

   연번  호선
3   4   1
4   5   1

In [23]:
df.iloc[[0,1,3], [1,3]]

   호선    2021년1월
0   1  1418813.0
1   1   746651.0
3   1   784896.0

In [84]:
df.iloc[:,1:4]

     호선        역명    2021년1월
0     1    서울역(1)  1418813.0
1     1     시청(1)   746651.0
2     1        종각  1241008.0
3     1   종로3가(1)   784896.0
4     1      종로5가   848774.0
..   ..       ...        ...
289   9      송파나루   184506.0
290   9      한성백제    87358.0
291   9  올림픽공원(9)   201840.0
292   9      둔촌오륜    35654.0
293   9    중앙보훈병원   332163.0

[294 rows x 3 columns]

In [24]:
import pandas as pd
df=pd.read_csv('c:/data/traffic/data2.csv')
df.head()

,호선,역번호,역 명,계,일평균,1월,2월,3월,4월,5월,6월,7월
0,1,150,서울역(1),19799600,93562,2823972,2542481,2885932,2918104,2993718,2770656,2864737
1,1,151,시청(1),9478426,44701,1367861,1114504,1380702,1432476,1460584,1334755,1387544
2,1,152,종각,16783116,78856,2529090,2098588,2445715,2433679,2496189,2269648,2510207
3,1,153,종로3가(1),11553939,54481,1729440,1465221,1692299,1638929,1734230,1600924,1692896
4,1,154,종로5가,10379864,49299,1532069,1303823,1558679,1532793,1571939,1423812,1456749

In [25]:
df2=df.iloc[:,4:12]
df2.describe()
#e+05==x10**5

,일평균,1월,2월,3월,4월,5월,6월,7월
count,288.000000,2.880000e+02,2.880000e+02,2.880000e+02,2.880000e+02,2.880000e+02,2.880000e+02,2.880000e+02
mean,25914.190972,7.807080e+05,6.649665e+05,8.136008e+05,8.205614e+05,8.433722e+05,7.672591e+05,8.012688e+05
std,21553.034548,6.739985e+05,5.781245e+05,6.723024e+05,6.665224e+05,6.855378e+05,6.304334e+05,6.776332e+05
min,1429.000000,3.648900e+04,3.325400e+04,4.640200e+04,4.791400e+04,4.845500e+04,4.629300e+04,4.839500e+04
25%,12176.250000,3.462888e+05,2.965675e+05,3.729890e+05,3.781295e+05,4.006558e+05,3.637908e+05,3.800970e+05
50%,20260.500000,5.955250e+05,5.089835e+05,6.450845e+05,6.564945e+05,6.791040e+05,5.981110e+05,6.103110e+05
75%,31115.250000,9.412722e+05,7.976460e+05,9.684600e+05,9.772028e+05,9.963918e+05,9.032735e+05,9.695805e+05
max,142123.000000,4.749571e+06,3.901121e+06,4.367422e+06,4.234069e+06,4.365377e+06,4.106734e+06,4.778586e+06

In [26]:
print(df2['1월'].mean())

780708.0381944445

In [27]:
df2.sum(axis=0)

일평균      7463287
1월     224843915
2월     191510348
3월     234317028
4월     236321689
5월     242891189
6월     220970623
7월     230765406
dtype: int64

In [28]:
df2

       일평균       1월       2월       3월       4월       5월       6월       7월
0    93562  2823972  2542481  2885932  2918104  2993718  2770656  2864737
1    44701  1367861  1114504  1380702  1432476  1460584  1334755  1387544
2    78856  2529090  2098588  2445715  2433679  2496189  2269648  2510207
3    54481  1729440  1465221  1692299  1638929  1734230  1600924  1692896
4    49299  1532069  1303823  1558679  1532793  1571939  1423812  1456749
..     ...      ...      ...      ...      ...      ...      ...      ...
283   6146   172531   154426   189654   200834   204882   190174   212000
284   3229    89927    77050    95084   100688   120700   101026   106923
285  12209   306660   255489   367268   378991   448814   452593   464731
286   1429    36489    33254    46402    47914    48455    46293    48395
287  11423   322250   281153   344386   369543   386127   364045   405519

[288 rows x 8 columns]

In [29]:
df2.head().sum(axis=1)

0    19893162
1     9523127
2    16861972
3    11608420
4    10429163
dtype: int64

In [30]:
print(df2['1월'].var())

454274023051.7721

In [31]:
f1=lambda x : x.max() - x.min()

In [32]:
df2[['1월','2월','3월']].apply(f1, axis=0)

1월    4713082
2월    3867867
3월    4321020
dtype: int64

In [33]:
df2[['1월','2월','3월','4월','5월']].head().apply(f1, axis=1)
                #tale() 끝에서부터 5행

0    451237
1    346080
2    430502
3    269009
4    268116
dtype: int64

In [34]:
import pandas as pd
input_file = 'c:/data/traffic/data.csv'
output_file = 'c:/data/traffic/output2.csv'
df=pd.read_csv(input_file,encoding='ms949')
df.to_csv(output_file, index=False, encoding='ms949')